### ISSUE TITLE
Feature: A Login Screen

### ISSUE THREAD

**Issue by JerJohn15** [JerJohn15/Java-Showcase#3]
Create a login screen using Java FX.

- [sample front end login](http://www.genuinecoder.com/2016/05/javafx-materia-design-setting-up-login-application.html)

- [x] Login Screen should be created using Scene builder method and without it.
- [x] UI Needs to be created. 
- [ ] Maybe add back end stuff, or save it for online functionality.
