### ISSUE TITLE
Feature: Music Artist Gallery

### ISSUE THREAD

**Issue by JerJohn15** [JerJohn15/Java-Showcase#8]
Create a Music Artist Gallery which shows popular music artists from around the world. 

**Criteria**:

- [ ]  should create a database from artists from each part of the continent 
- [ ] content should contain general information about the artist (Name, Origin of birth, birthdate, death date, hit song, link to hit song or video)

**To Do:**

- [ ] Prototype application design 
- [ ] Two Designs will be implemented. (1) The primary one will contain two button that will be used to navigate the images and descriptions, while the secondary one will use a slider. (The slider is used just to experiment performance quality with both the images and content together)
